apiVersion: v2
appVersion: 1.0.0
description: Codefresh gitops runtime umbrella chart
name: codefresh-gitops-runtime
version: 25.11-0-cr-32102-update-pr-ep-to-25.11
dependencies:
  - name: gitops-runtime
    repository: oci://quay.io/codefresh/dev
    version: 25.11-0-cr-32102-update-pr-ep-to-25.11
